# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'IGNApp' do
	pod 'SwiftyJSON'
	pod 'SDWebImage', '~> 4.0'
	pod 'XLPagerTabStrip'
end
